const API='https://pisobelmez.cumstadistica.chatgpt.site/api/listings';
const samples=[{id:-1,title:'Piso luminoso junto al centro',type:'Piso',area:'Centro · Belmez',price:420,rooms:3,baths:1,size:86,image:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=82'},{id:-2,title:'Casa tranquila con patio',type:'Casa',area:'Barrio El Hoyo · Belmez',price:490,rooms:3,baths:2,size:112,image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=82'},{id:-3,title:'Habitación para estudiante',type:'Habitación',area:'Cerca de la EPS · Belmez',price:190,rooms:1,baths:1,size:18,image:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=82'}];
let listings=samples,installPrompt=null;const $=s=>document.querySelector(s),all=s=>document.querySelectorAll(s);
function render(){const type=$('#type').value,max=Number($('#price').value);const rows=listings.filter(x=>(type==='all'||x.type===type)&&x.price<=max);$('#count').textContent=`${rows.length} OPCIONES DISPONIBLES`;$('#grid').innerHTML=rows.map(x=>`<article class="card"><div>${x.image?`<img src="${escapeHtml(x.image)}" alt="${escapeHtml(x.title)}">`:'<div class="fallback">⌂</div>'}</div><div class="cardBody"><strong class="price">${x.price} € <small>/ mes</small></strong><h3>${escapeHtml(x.title)}</h3><p>⌖ ${escapeHtml(x.area)}</p><div class="meta"><span>▦ ${x.rooms} hab.</span><span>◫ ${x.baths} baño${x.baths>1?'s':''}</span><span>↔ ${x.size} m²</span></div>${x.phone?`<a class="contact" href="tel:${x.phone.replace(/\s/g,'')}">Llamar al casero</a>`:'<span class="contact">Anuncio de ejemplo</span>'}</div></article>`).join('')||'<p class="loading">No hay alojamientos con estos filtros.</p>'}
function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),4500)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});async function install(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else $('#installModal').classList.remove('hidden')}
$('#install').onclick=install;$('#mobileInstall').onclick=install;$('#search').onclick=()=>{$('#alojamientos').scrollIntoView();render()};$('#type').onchange=render;$('#price').onchange=render;all('[data-publish]').forEach(b=>b.onclick=()=>$('#publishModal').classList.remove('hidden'));all('[data-close]').forEach(b=>b.onclick=()=>$('#publishModal').classList.add('hidden'));all('[data-close-install]').forEach(b=>b.onclick=()=>$('#installModal').classList.add('hidden'));
$('#listingForm').onsubmit=async e=>{e.preventDefault();const button=$('#submit');button.disabled=true;button.textContent='Publicando…';try{const r=await fetch(API,{method:'POST',body:new FormData(e.target)});const item=await r.json();if(!r.ok)throw new Error(item.error||'No se pudo publicar.');listings=[item,...listings];render();$('#publishModal').classList.add('hidden');e.target.reset();toast('¡Tu anuncio ya está publicado!');$('#alojamientos').scrollIntoView()}catch(err){toast(err.message)}finally{button.disabled=false;button.textContent='Publicar ahora'}};
fetch(API).then(r=>r.ok?r.json():[]).then(rows=>{if(rows.length)listings=[...rows,...samples];render()}).catch(()=>render());if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
